version: '3.9'

services:
  # =app
  app:
    image: "sindriainc/nginx-php:${NGINX_PHP_TAG}-${NGINX_PHP_VERSION}"
    container_name: "${APP_NAME}"
    #command: tail -f /dev/null
    volumes:
      #- "./${CODE_PATH}:${APP_CODE_PATH}"
      - "${BASE_PATH}/${PROJECT_PATH}/${CODE_PATH}:${APP_CODE_PATH}"
    hostname: "${APP_NAME}.local"
    #ports:
    #  - "8082:80"
    networks:
      default:
        ipv4_address: "${APP_IP_ADDRESS}"
        aliases:
          - "${APP_NAME}.local"
    #networks:
    #  vpc_xdev:
    #    ipv4_address: "${APP_IP_ADDRESS}"
    #    aliases:
    #      - "${APP_NAME}.local"

  # =db
  db:
    image: "sindriainc/mariadb:${MARIADB_TAG}-${MARIADB_VERSION}"
    container_name: "${AUTH_NAME}-db"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      #- "${APP_DATA_PATH}/db/:/var/lib/mysql:delegated"
      - "/var/lib/mysql"
    hostname: "${AUTH_NAME}-db.local"
    #ports:
    #  - "3306:3306"
    networks:
      default:
        ipv4_address: "${DB_IP_ADDRESS}"
        aliases:
          - "${AUTH_NAME}-db.local"
    #networks:
    #  vpc_xdev:
    #    ipv4_address: "${DB_IP_ADDRESS}"
    #    aliases:
    #      - "${AUTH_NAME}-db.local"

  # =auth
  auth:
    image: "jboss/keycloak:${KEYCLOAK_TAG}"
    container_name: "${AUTH_NAME}"
    #command: tail -f /dev/null
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      - PROXY_ADDRESS_FORWARDING=${PROXY_ADDRESS_FORWARDING}
      - DB_VENDOR=${DB_VENDOR}
      - DB_DATABASE=${DB_DATABASE}
      - DB_ADDR=${DB_ADDR}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    hostname: "${AUTH_NAME}.local"
    ports:
      - "8083:8080"
    networks:
      default:
        ipv4_address: "${AUTH_IP_ADDRESS}"
        aliases:
          - "${AUTH_NAME}.local"
    #networks:
    #  vpc_xdev:
    #    ipv4_address: "${AUTH_IP_ADDRESS}"
    #    aliases:
    #      - "${AUTH_NAME}.local"

# =networks
networks:
  default:
    name: "vpc_xp-web"
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}

# =networks
#networks:
#  vpc_xdev:
#    external: true
